<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/aco95/projects/under-the-sea-challenge/static/models/Jellyfish.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	type $$Props = Props<THREE.Group>;
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

	export const ref = new Group();

	type GLTFResult = {
		nodes: {
			Tentacles: THREE.Mesh;
			Sphere: THREE.Mesh;
			Plane: THREE.Mesh;
			Plane_1: THREE.Mesh;
		};
		materials: {
			['Material.003']: THREE.MeshStandardMaterial;
			['Material.004']: THREE.MeshPhysicalMaterial;
			['Material.006']: THREE.MeshPhysicalMaterial;
			['Material.007']: THREE.MeshPhysicalMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/models/Jellyfish.glb');

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.Tentacles.geometry}
			material={gltf.materials['Material.003']}
			position={[0.09, 0.64, -0.1]}
			rotation={[0, 0.54, 0]}
			scale={[0.1, 0.12, 0.1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Sphere.geometry}
			material={gltf.materials['Material.004']}
			position={[0, 0.39, 0]}
			scale={0.31}
		/>
		<T.Group position={[0, 0.25, 0]} scale={[0.3, 0.11, 0.3]}>
			<T.Mesh geometry={gltf.nodes.Plane.geometry} material={gltf.materials['Material.006']} />
			<T.Mesh geometry={gltf.nodes.Plane_1.geometry} material={gltf.materials['Material.007']} />
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
