<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/aco95/projects/under-the-sea-challenge/static/models/Lionfish.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useGltfAnimations } from '@threlte/extras';

	type $$Props = Props<THREE.Group>;
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

	export const ref = new Group();

	type ActionName =
		| 'Fish_Armature|Attack'
		| 'Fish_Armature|Death'
		| 'Fish_Armature|Out_Of_Water'
		| 'Fish_Armature|Swimming_Fast'
		| 'Fish_Armature|Swimming_Impulse'
		| 'Fish_Armature|Swimming_Normal';
	type GLTFResult = {
		nodes: {
			Lionfish_1: THREE.SkinnedMesh;
			Lionfish_2: THREE.SkinnedMesh;
			Lionfish_3: THREE.SkinnedMesh;
			Lionfish_4: THREE.SkinnedMesh;
			Main1: THREE.Bone;
		};
		materials: {
			Lionfish_Fins: THREE.MeshStandardMaterial;
			Lionfish_Main: THREE.MeshStandardMaterial;
			Lionfish_Light: THREE.MeshStandardMaterial;
			Eyes: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/models/Lionfish.glb');
	export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref);

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Root_Scene">
			<T.Group name="RootNode">
				<T.Group name="Fish_Armature" rotation={[-Math.PI / 2, 0, 0]} scale={15}>
					<T is={gltf.nodes.Main1} />
				</T.Group>
				<T.Group name="Lionfish" rotation={[-Math.PI / 2, 0, 0]} scale={15}>
					<T.SkinnedMesh
						name="Lionfish_1"
						geometry={gltf.nodes.Lionfish_1.geometry}
						material={gltf.materials.Lionfish_Fins}
						skeleton={gltf.nodes.Lionfish_1.skeleton}
					/>
					<T.SkinnedMesh
						name="Lionfish_2"
						geometry={gltf.nodes.Lionfish_2.geometry}
						material={gltf.materials.Lionfish_Main}
						skeleton={gltf.nodes.Lionfish_2.skeleton}
					/>
					<T.SkinnedMesh
						name="Lionfish_3"
						geometry={gltf.nodes.Lionfish_3.geometry}
						material={gltf.materials.Lionfish_Light}
						skeleton={gltf.nodes.Lionfish_3.skeleton}
					/>
					<T.SkinnedMesh
						name="Lionfish_4"
						geometry={gltf.nodes.Lionfish_4.geometry}
						material={gltf.materials.Eyes}
						skeleton={gltf.nodes.Lionfish_4.skeleton}
					/>
				</T.Group>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
