<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/aco95/projects/under-the-sea-challenge/static/models/MandarinFish.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
	import * as THREE from 'three';
	import { Group } from 'three';
	import {
		T,
		type Props,
		type Events,
		type Slots,
		forwardEventHandlers,
		useThrelte
	} from '@threlte/core';
	import { useGltf, useGltfAnimations } from '@threlte/extras';
	import { transitionTo } from '$lib/models/AnimationUtils';

	type $$Props = Props<THREE.Group>;
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

	export const ref = new Group();

	type ActionName =
		| 'Fish_Armature|Attack'
		| 'Fish_Armature|Death'
		| 'Fish_Armature|Out_Of_Water'
		| 'Fish_Armature|Swimming_Fast'
		| 'Fish_Armature|Swimming_Impulse'
		| 'Fish_Armature|Swimming_Normal';
	type GLTFResult = {
		nodes: {
			MandarinFish_1: THREE.SkinnedMesh;
			MandarinFish_2: THREE.SkinnedMesh;
			MandarinFish_3: THREE.SkinnedMesh;
			MandarinFish_4: THREE.SkinnedMesh;
			Main1: THREE.Bone;
		};
		materials: {
			MandarinFish_Main: THREE.MeshStandardMaterial;
			MandarinFish_Light: THREE.MeshStandardMaterial;
			MandarinFish_Dark: THREE.MeshStandardMaterial;
			Eyes: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/models/MandarinFish.glb');
	export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref);

	const component = forwardEventHandlers();

	$: if ($gltf) {
		$gltf.materials.MandarinFish_Main.side = THREE.DoubleSide;
		$gltf.materials.MandarinFish_Dark.side = THREE.DoubleSide;
		$gltf.materials.MandarinFish_Light.side = THREE.DoubleSide;
	}

	let currentActionKey: ActionName = 'Fish_Armature|Swimming_Normal';

	$: $actions[currentActionKey]?.play();

	$: if ($actions['Fish_Armature|Death']) {
		$actions['Fish_Armature|Death'].loop = THREE.LoopOnce;
		$actions['Fish_Armature|Death'].clampWhenFinished = true;
	}

	export function swim() {
		currentActionKey = transitionTo($actions, currentActionKey, 'Fish_Armature|Swimming_Normal');
	}

	export function die() {
		currentActionKey = transitionTo($actions, currentActionKey, 'Fish_Armature|Death', 0.5, true);
		const action = $actions['Fish_Armature|Death'];
		if (action) {
			action.getMixer().addEventListener('finished', () => {
				ref.rotation.z = Math.PI;
			});
		}
	}
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Root_Scene">
			<T.Group name="RootNode">
				<T.Group name="Fish_Armature" rotation={[-Math.PI / 2, 0, 0]} scale={15}>
					<T is={gltf.nodes.Main1} />
				</T.Group>
				<T.Group name="MandarinFish" rotation={[-Math.PI / 2, 0, 0]} scale={15}>
					<T.SkinnedMesh
						name="MandarinFish_1"
						geometry={gltf.nodes.MandarinFish_1.geometry}
						material={gltf.materials.MandarinFish_Main}
						skeleton={gltf.nodes.MandarinFish_1.skeleton}
					/>
					<T.SkinnedMesh
						name="MandarinFish_2"
						geometry={gltf.nodes.MandarinFish_2.geometry}
						material={gltf.materials.MandarinFish_Light}
						skeleton={gltf.nodes.MandarinFish_2.skeleton}
					/>
					<T.SkinnedMesh
						name="MandarinFish_3"
						geometry={gltf.nodes.MandarinFish_3.geometry}
						material={gltf.materials.MandarinFish_Dark}
						skeleton={gltf.nodes.MandarinFish_3.skeleton}
					/>
					<T.SkinnedMesh
						name="MandarinFish_4"
						geometry={gltf.nodes.MandarinFish_4.geometry}
						material={gltf.materials.Eyes}
						skeleton={gltf.nodes.MandarinFish_4.skeleton}
					/>
				</T.Group>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
