<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/aco95/projects/under-the-sea-challenge/static/models/Stingray.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useGltfAnimations } from '@threlte/extras';

	type $$Props = Props<THREE.Group>;
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

	export const ref = new Group();

	type ActionName = 'Armature|Swim';
	type GLTFResult = {
		nodes: {
			MantaRay_1: THREE.SkinnedMesh;
			MantaRay_2: THREE.SkinnedMesh;
			Root: THREE.Bone;
		};
		materials: {
			Bottom: THREE.MeshStandardMaterial;
			Top: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>(`/models/MantaRay.glb?${Math.random()}`);
	export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref);

	$: if ($actions) {
		swim();
	}

	function swim() {
		$actions['Armature|Swim']?.play();
	}

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Root_Scene">
			<T.Group name="RootNode">
				<T.Group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={50}>
					<T is={gltf.nodes.Root} />
				</T.Group>
				<T.Group name="MantaRay" position={[0, 0, 0.8]} rotation={[-Math.PI / 2, 0, 0]} scale={50}>
					<T.SkinnedMesh
						name="MantaRay_1"
						geometry={gltf.nodes.MantaRay_1.geometry}
						material={gltf.materials.Bottom}
						skeleton={gltf.nodes.MantaRay_1.skeleton}
					/>
					<T.SkinnedMesh
						name="MantaRay_2"
						geometry={gltf.nodes.MantaRay_2.geometry}
						material={gltf.materials.Top}
						skeleton={gltf.nodes.MantaRay_2.skeleton}
					/>
				</T.Group>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
