<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/aco95/projects/under-the-sea-challenge/static/models/Puffer.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
	import * as THREE from 'three';
	import { Group } from 'three';
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useGltfAnimations } from '@threlte/extras';

	type $$Props = Props<THREE.Group>;
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

	export const ref = new Group();

	type ActionName =
		| 'Fish_Armature|Attack'
		| 'Fish_Armature|Death'
		| 'Fish_Armature|Out_Of_Water'
		| 'Fish_Armature|Swimming_Fast'
		| 'Fish_Armature|Swimming_Impulse'
		| 'Fish_Armature|Swimming_Normal';
	type GLTFResult = {
		nodes: {
			Pufferfish002_1: THREE.SkinnedMesh;
			Pufferfish002_2: THREE.SkinnedMesh;
			Pufferfish_1: THREE.SkinnedMesh;
			Pufferfish_2: THREE.SkinnedMesh;
			Pufferfish_3: THREE.SkinnedMesh;
			Pufferfish_4: THREE.SkinnedMesh;
			Main1: THREE.Bone;
		};
		materials: {
			Pufferfish_Main: THREE.MeshStandardMaterial;
			Pufferfish_Light: THREE.MeshStandardMaterial;
			Puffefish_Black: THREE.MeshStandardMaterial;
			Eyes: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>(`/models/Puffer.glb?${Math.random()}`);
	export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref);

	const component = forwardEventHandlers();

	$: if ($gltf) {
		$gltf.materials.Pufferfish_Main.side = THREE.DoubleSide; // TODO: check this
	}

	$: if ($actions) {
		swim();
	}

	export function swim() {
		$actions['Fish_Armature|Swimming_Normal']?.play();
	}

	export function swimFast() {
		$actions['Fish_Armature|Swimming_Fast']?.play();
	}

	export function attack() {
		$actions['Fish_Armature|Attack']?.play();
	}
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Root_Scene">
			<T.Group name="RootNode">
				<T.Group name="Pufferfish001" rotation={[-Math.PI / 2, 0, 0]} scale={20} />
				<T.Group name="Fish_Armature" rotation={[-Math.PI / 2, 0, 0]} scale={20}>
					<T is={gltf.nodes.Main1} />
				</T.Group>
				<T.Group name="Pufferfish002" rotation={[-Math.PI / 2, 0, 0]} scale={20}>
					<T.SkinnedMesh
						name="Pufferfish002_1"
						geometry={gltf.nodes.Pufferfish002_1.geometry}
						material={gltf.materials.Pufferfish_Main}
						skeleton={gltf.nodes.Pufferfish002_1.skeleton}
					/>
					<T.SkinnedMesh
						name="Pufferfish002_2"
						geometry={gltf.nodes.Pufferfish002_2.geometry}
						material={gltf.materials.Pufferfish_Light}
						skeleton={gltf.nodes.Pufferfish002_2.skeleton}
					/>
				</T.Group>
				<T.Group name="Pufferfish" rotation={[-Math.PI / 2, 0, 0]} scale={20}>
					<T.SkinnedMesh
						name="Pufferfish_1"
						geometry={gltf.nodes.Pufferfish_1.geometry}
						material={gltf.materials.Pufferfish_Main}
						skeleton={gltf.nodes.Pufferfish_1.skeleton}
					/>
					<T.SkinnedMesh
						name="Pufferfish_2"
						geometry={gltf.nodes.Pufferfish_2.geometry}
						material={gltf.materials.Pufferfish_Light}
						skeleton={gltf.nodes.Pufferfish_2.skeleton}
					/>
					<T.SkinnedMesh
						name="Pufferfish_3"
						geometry={gltf.nodes.Pufferfish_3.geometry}
						material={gltf.materials.Puffefish_Black}
						skeleton={gltf.nodes.Pufferfish_3.skeleton}
					/>
					<T.SkinnedMesh
						name="Pufferfish_4"
						geometry={gltf.nodes.Pufferfish_4.geometry}
						material={gltf.materials.Eyes}
						skeleton={gltf.nodes.Pufferfish_4.skeleton}
					/>
				</T.Group>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
