<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/aco95/projects/under-the-sea-challenge/static/models/Shark.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useGltfAnimations } from '@threlte/extras';

	type $$Props = Props<THREE.Group>;
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

	export const ref = new Group();

	type ActionName =
		| 'SharkArmature|SharkArmature|SharkArmature|Swim_Bite|SharkArmature|Swim_Bite'
		| 'SharkArmature|SharkArmature|SharkArmature|Swim_Fast|SharkArmature|Swim_Fast'
		| 'SharkArmature|SharkArmature|SharkArmature|Swim|SharkArmature|Swim';
	type GLTFResult = {
		nodes: {
			Shark: THREE.SkinnedMesh;
			Shark001: THREE.SkinnedMesh;
			Abdomen: THREE.Bone;
			Center: THREE.Bone;
			Root: THREE.Bone;
		};
		materials: {
			AtlasMaterial: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/models/Shark.glb');
	export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref);

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Root_Scene">
			<T.Group name="RootNode">
				<T.Group name="SharkArmature" rotation={[-Math.PI / 2, 0, 0]} scale={50}>
					<T is={gltf.nodes.Abdomen} />
					<T is={gltf.nodes.Center} />
					<T is={gltf.nodes.Root} />
				</T.Group>
				<T.SkinnedMesh
					name="Shark"
					geometry={gltf.nodes.Shark.geometry}
					material={gltf.materials.AtlasMaterial}
					skeleton={gltf.nodes.Shark.skeleton}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={50}
				/>
				<T.SkinnedMesh
					name="Shark001"
					geometry={gltf.nodes.Shark001.geometry}
					material={gltf.materials.AtlasMaterial}
					skeleton={gltf.nodes.Shark001.skeleton}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={50}
				/>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
