<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/aco95/projects/under-the-sea-challenge/static/models/Swordfish.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
	import * as THREE from 'three';
	import { Group } from 'three';
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useGltfAnimations } from '@threlte/extras';
	import { transitionTo } from '$lib/models/AnimationUtils';

	type $$Props = Props<THREE.Group>;
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

	export const ref = new Group();

	type ActionName =
		| 'Fish_Armature|Attack'
		| 'Fish_Armature|Death'
		| 'Fish_Armature|Out_Of_Water'
		| 'Fish_Armature|Swimming_Fast'
		| 'Fish_Armature|Swimming_Impulse'
		| 'Fish_Armature|Swimming_Normal';
	type GLTFResult = {
		nodes: {
			Swordfish_1: THREE.SkinnedMesh;
			Swordfish_2: THREE.SkinnedMesh;
			Swordfish_3: THREE.SkinnedMesh;
			Swordfish_4: THREE.SkinnedMesh;
			Main1: THREE.Bone;
		};
		materials: {
			Swordfish_Light: THREE.MeshStandardMaterial;
			Swordfish_Main: THREE.MeshStandardMaterial;
			Swordfish_Dark: THREE.MeshStandardMaterial;
			Eyes: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>(`/models/Swordfish.glb?${Math.random()}`);
	export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref);

	const component = forwardEventHandlers();

	$: if ($gltf) {
		$gltf.materials.Swordfish_Main.side = THREE.DoubleSide;
		$gltf.materials.Swordfish_Dark.side = THREE.DoubleSide;
		$gltf.materials.Swordfish_Light.side = THREE.DoubleSide;
	}

	let currentActionKey: ActionName = 'Fish_Armature|Swimming_Normal';

	$: $actions[currentActionKey]?.play();

	export function swimFast() {
		$actions['Fish_Armature|Swimming_Fast']?.play();
	}

	export function swim() {
		currentActionKey = transitionTo($actions, currentActionKey, 'Fish_Armature|Swimming_Normal');
	}

	export function attack() {
		currentActionKey = transitionTo($actions, currentActionKey, 'Fish_Armature|Attack');
	}
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Root_Scene">
			<T.Group name="RootNode">
				<T.Group name="Fish_Armature" rotation={[-Math.PI / 2, 0, 0]} scale={[25, 70, 25]}>
					<T is={gltf.nodes.Main1} />
				</T.Group>
				<T.Group name="Swordfish" rotation={[-Math.PI / 2, 0, 0]} scale={[25, 70, 25]}>
					<T.SkinnedMesh
						name="Swordfish_1"
						geometry={gltf.nodes.Swordfish_1.geometry}
						material={gltf.materials.Swordfish_Light}
						skeleton={gltf.nodes.Swordfish_1.skeleton}
					/>
					<T.SkinnedMesh
						name="Swordfish_2"
						geometry={gltf.nodes.Swordfish_2.geometry}
						material={gltf.materials.Swordfish_Main}
						skeleton={gltf.nodes.Swordfish_2.skeleton}
					/>
					<T.SkinnedMesh
						name="Swordfish_3"
						geometry={gltf.nodes.Swordfish_3.geometry}
						material={gltf.materials.Swordfish_Dark}
						skeleton={gltf.nodes.Swordfish_3.skeleton}
					/>
					<T.SkinnedMesh
						name="Swordfish_4"
						geometry={gltf.nodes.Swordfish_4.geometry}
						material={gltf.materials.Eyes}
						skeleton={gltf.nodes.Swordfish_4.skeleton}
					/>
				</T.Group>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
